Show errors on stderr

diff --git a/scripts/bin/screenshot b/scripts/bin/screenshot
--- a/scripts/bin/screenshot
+++ b/scripts/bin/screenshot
@@ -11,12 +11,12 @@ while test $# -gt 0; do
       ;;
     -*|--*)
       # We need to catch this or we would accept REQUESTED_OUTPUT values that grim treats as options
-      echo "Unknown option $1"
+      echo "Unknown option $1" >&2
       exit 1
       ;;
     *)
       if test ! -z "$REQUESTED_OUTPUT"; then
-        echo "Error: multiple output files specified"
+        echo "Error: multiple output files specified" >&2
         exit 1
       fi
       REQUESTED_OUTPUT="$1"
@@ -49,7 +49,7 @@ done
 # Check if we have permission to write to the file
 if ! touch "$OUTPUT_FILE" 2>/dev/null ; then
     ERROR_MESSAGE=$(touch "$OUTPUT_FILE" 2>&1 | sed 's/.*:\s*//')
-    echo "Can't save to $OUTPUT_FILE: $ERROR_MESSAGE"
+    echo "Can't save to $OUTPUT_FILE: $ERROR_MESSAGE" >&2
     exit 1
 fi
 rm "$OUTPUT_FILE"
@@ -57,6 +57,6 @@ rm "$OUTPUT_FILE"
 if $SNAP/usr/bin/grim "$OUTPUT_FILE"; then
   echo "Saved to $OUTPUT_FILE"
 else
-  echo "Failed to save screenshot to $OUTPUT_FILE"
+  echo "Failed to save screenshot to $OUTPUT_FILE" >&2
   exit 1
 fi
