if trying to enable the launcher on an armhf system. ten we throw an error

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -113,6 +113,11 @@ fi
 
 # Start or stop the launcher
 if [ "$(snapctl get launcher)" = "true" ]; then
+  if [ $(uname -m) = "arm" ]; then
+    echo "Cannot enable the launcher on an armhf system"
+    exit 1
+  fi
+
   if snapctl services "$SNAP_INSTANCE_NAME.launcher" | grep -q inactive; then
     snapctl start --enable "$SNAP_INSTANCE_NAME.launcher" 2>&1 || true
   fi
